# This program esitmates distance left in a route based on number of jumps
# and current / maximum just distance of the ship.
#
print("|___________________________________________________|")
print("| Elite: Dangerous Distance Left Estimation Program |")
print("| AshleighTheCutie, Tue 21 Jul 2020 18:15:38 CDT    |")
print("\---------------------------------------------------/")
print("")
print("Number of jumps left: ")
jumpsLeft = input("? ")
print("")
print("Current Jump Range: ")
minJumpRange = input("? ")
print("")
print("Maximum Jump Range: ")
maxJumpRange = input("? ")
print("")
print("Entered Values:")
print("Number of jumps left: " + jumpsLeft)
print("Current jump range: " + minJumpRange)
print("Maximum jump range: " + maxJumpRange)
print("")
print("Estimated distance:")
lowerDistance = float(jumpsLeft)*float(minJumpRange)
upperDistance = float(jumpsLeft)*float(maxJumpRange)
print("Minimum Distance (closest to actual distance): " + str(lowerDistance))
print("Maximum Distance: " + str(upperDistance))
avgDivisor = float(lowerDistance) + float(upperDistance)
avgDistance = float(avgDivisor) / 2
print("Average Distance: " + str(avgDistance))
