# This program esitmates number of jumps left in a route based on distance
# to go and current / maximum jump distance of the ship.
#
print("|___________________________________________________|")
print("| Elite: Dangerous Jumps Left Estimation Program    |")
print("| AshleighTheCutie, Wed 22 Jul 2020 13:53:41 CDT    |")
print("\---------------------------------------------------/")
print("")
print("Distance left: ")
distanceLeft = input("? ")
print("")
print("Current Jump Range: ")
minJumpRange = input("? ")
print("")
print("Maximum Jump Range: ")
maxJumpRange = input("? ")
print("")
print("Entered Values:")
print("Distance left: " + distanceLeft)
print("Current jump range: " + minJumpRange)
print("Maximum jump range: " + maxJumpRange)
print("")
print("Estimated number of jumps:")
lowerDistance = float(distanceLeft)/float(minJumpRange)
upperDistance = float(distanceLeft)/float(maxJumpRange)
print("Minimum Jumps: (closest to actual number of jumps): " + str(lowerDistance))
print("Maximum Jumps: " + str(upperDistance))
avgDivisor = float(lowerDistance) + float(upperDistance)
avgDistance = float(avgDivisor) / 2
print("Average Jumps: " + str(avgDistance))
